version: "3"

name: gitea_compose

services:
  server:
    image: gitea/gitea:dev-rootless
    container_name: gitea
    user: "1000"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/data/:/var/lib/gitea/data
      - /home/git/config/:/etc/gitea
    ports:
      - "8880:3000" # see also: ./nginx.conf
      - "127.0.0.1:2222:22"
